name: CI - Tests unitaires et fonctionnels

on: [push, pull_request]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Init projet
        uses: actions/checkout@v2
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.4
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python3 mysite/manage.py test