name: CI - Tests unitaires et fonctionnels

on: [push, pull_request]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Init projet
        uses: actions/checkout@v2
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.4
      - name: Run tests
        registry-url: https://github.com/YeSylvie/iim-a4-django/tree/develop/mysite
        run: python3 manage.py test